[package]
name = "tsscaffold"
version = "0.1.0"
authors = ["Ville Peurala <ville.peurala@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.3.1"
serde = "1.0"
serde_yaml = "0.8"
structopt = "0.3"